name: DockerHub-CI

on:
  push:
    branches:
    - master
    - latest
    tags: 
    - release-*

jobs:
  dockerhub-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Map git ref -> docker tag
        run: |
          # Determine docker tag based on git ref
          if [[ $GITHUB_REF == refs/heads/master ]]; then
            TAG="dev-latest"
          elif [[ $GITHUB_REF == refs/heads/latest ]]; then
            TAG="latest"
          elif [[ $GITHUB_REF == refs/tags/release-* ]]; then
            TAG=${GITHUB_REF#refs/tags/release-}
          fi
          echo Mapped git ref $GITHUB_REF to docker tag $TAG
          # export result to environment variable available to next steps
          echo ::set-env name=GS_DOCKER_TAG::$TAG
      - name: Build and push xap-enterprise
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./xap-enterprise
          repository: gigaspaces/xap-enterprise
          tags: ${{ env.GS_DOCKER_TAG }}
      - name: Build and push insightedge-enterprise
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./insightedge-enterprise
          repository: gigaspaces/insightedge-enterprise
          tags:  ${{ env.GS_DOCKER_TAG }}
